### ISSUE TITLE
Table of contents (scrollspy) is not working

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#17] opened 2021-01-06 09:53 UTC
Both for pre-existing content ([example](https://grrr-www.clarin-dev.eu/resource-families/historical-corpora)) and new content ([example](https://grrr-www.clarin-dev.eu/news/news-example-table-contents)).

Additionally the styling of the Table of Contents block is not up to date with the new design (solid box around it).

**Comment by andmor-** [comment] 2021-02-11 12:10
I partially fixed this issue and the TOC now appears for new content. This was caused by 2 issues:

1. the file [clarin_bootstrap.theme](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/clarin_bootstrap.theme) was not being included by the build [gulpfile.js](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/gulpfile.js#L59).
2. the file [toc.js](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/js/toc.js) was committed to the wrong place `/js/toc.js` (while it should have been `/assets/scripts`) and was also not picked up by the build.


### Current problems with the TOC to be fixed:
-  it does not float with page scroll 
-  it is located in an odd place. 
[see](https://grrr-www.clarin-dev.eu/news/news-example-table-contents)

----
Note: the inclusion of [clarin_bootstrap.theme](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/clarin_bootstrap.theme) should also bring other fixes/functionalities:
1. it looks for the field [field_see_also_links](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/clarin_bootstrap.theme#L32) which I don't know which content type has
2. it makes some [button link blue in the views](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/clarin_bootstrap.theme#L12)
----

**Comment by andmor-** [comment] 2021-02-12 15:49
Another small issue to be fixed: 
- The TOC does not take into account the height of the top bar in case the user is logged in. When clicking on the TOC items the page lands on a slightly off positon

**Comment by andmor-** [comment] 2021-03-11 12:33
Continuing this in #33

**Closed as completed by andmor-** 2021-03-11 12:33 UTC
Labels: bug, GRRR
